# install.packages(c("arsenal", "BiocManager", "dplyr", "ggarchery", "ggplot2", "ggpubr", "MetBrewer", "openxlsx", "plotrix", "plyr", "PNWColors", "RColorBrewer", "scales", "stringi", "tidyr", "tidyverse", "wesanderson")

library(arsenal)
library(cowplot)
library(dplyr)
library(ggarchery)
library(ggplot2)
library(ggpubr)
library(MetBrewer)
library(openxlsx)
library(plotrix)
library(plyr)
library(PNWColors)
library(RColorBrewer)
library(scales)
library(stringi)
library(tidyr)
library(tidyverse)
library(wesanderson)


library(BiocManager)
# BiocManager::install(c("clusterProfiler", "ComplexHeatmap", "DESeq2", "DOSE", "EnhancedVolcano", "enrichplot", "ExperimentHub", "fgsea", "forcats", "GSEABase", "limma", "msigdb", "org.Mm.eg.db", "pheatmap", "ReactomePA", "sva", "VennDetail"))

library(clusterProfiler)
library(ComplexHeatmap)
library(DESeq2)
library(DOSE)
library(EnhancedVolcano)
library(enrichplot)
library(ExperimentHub)
library(fgsea)
library(forcats)
library(grid)
library(gridBase)
library(gridExtra)
library(GSEABase)
library(limma)
library(magick)
library(msigdb)
library(org.Mm.eg.db)
library(pheatmap)
library(ReactomePA)
library(sva)
library(VennDetail)



# Packages I haven't used
# install.packages(c("colorblindcheck", "ggrepel", "grid", "gridBase", "gridExtra", "igraph", "readr", "VennDiagram"))
# library(colorblindcheck)
# library(ggrepel)
# library(igraph)
# library(readr)
# library(VennDiagram)

# BiocManager::install(c("apeglm", "GOSemSim", "pathview", "vsn"))
# library(apeglm)
# library(GOSemSim)
# library(pathview)
# library(vsn)

# install.packages("devtools")
# devtools::install_github("BlakeRMills/MoMAColors")
# library(MoMAColors)
