# install.packages(c("RColorBrewer","openxlsx","ggplot2","readr","dplyr","stringi","grid","gridBase","gridExtra","ggrepel", "BiocManager", "igraph"))
# library(BiocManager)
# BiocManager::install(c("DESeq2","apeglm","vsn","EnhancedVolcano","pheatmap","pheatmap","limma","forcats", "clusterProfiler", "pathview", "enrichplot", "org.Mm.eg.db", "VennDetail"))

library(BiocManager)
library(DESeq2)
# library(apeglm)
# library(vsn)
library(EnhancedVolcano)
library(pheatmap)
library(openxlsx)
library(RColorBrewer)
library(MetBrewer)
library(colorblindcheck)
# library(readr)
library(ggplot2)
library(dplyr)
library(plyr)
library(stringi)
# library(grid)
# library(gridBase)
# library(gridExtra)
# library(ggrepel)
library(limma)
# library(forcats)
# library(clusterProfiler)
# library(pathview)
# library(enrichplot)
# library(igraph)
# library(org.Mm.eg.db)
# library(ReactomePA)
# library(tidyr)
library(VennDetail)
# library(VennDiagram)
# library(GOSemSim)
